name: NoVillagerSpawnedGolems
main: dev.shane.minecraft.novillagerspawnedgolems.NoVillagerSpawnedGolemsPlugin
version: ${version}
api-version: '${paperApiVersion}'
author: Shane
load: POSTWORLD
description: Blocks villager-spawned iron golems while allowing player-built golems.
commands: {}
permissions: {}
